return {
   {
      "nvim-treesitter/nvim-treesitter",
      tag = "v0.9.4",
      opts = {
         ensure_installed = {
            "javascript",
            "typescript",
            "css",
            "gitignore",
            "graphql",
            "http",
            "dockerfile",
            "python",
            "php",
            "c",
            "yaml",
            "c_sharp",
            "markdown",
            "markdown_inline",
            "html",
            "query",
            "tsx",
            "regex",
            "java",
            "json",
            "scss",
            "sql",
            "lua",
         },
         query_linter = {
            enable = true,
            use_virtual_text = true,
            lint_events = { "BufWrite", "CursorHold" },
         },
      },
   },
}
